### ISSUE TITLE
bug: can't add execution on a proposal

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#471] opened 2024-07-06 16:10 UTC
I've created a space with a Timelock execution, I've added the execution address as treasury address, but still I can't add any execution on a proposal, I can't also initiate a tx from the treasury page
https://snapshot.box/#/oeth:0x5930951688696Dfe718D5Dc6ee344CEc6d3c6A5E/create/nst2l

**Comment by Sekhmet** [comment] 2024-07-08 13:57
Looks like you added treasury on ETH, but execution strategy is configured on OP.



![Image](https://github.com/snapshot-labs/sx-monorepo/assets/1968722/1d461916-953b-4576-a1c9-ba24f4887547)



Addresses do match, but UI can't link those two together, because they are not really tied. You need to update space metadata to switch that treasury to be on Optimism.

**Comment by Sekhmet** [comment] 2024-07-29 21:40
Closing as it looks like it's not a bug. We can reopen if we think something is not working as intended.

**Closed by Sekhmet** 2024-07-29 21:40 UTC
Labels: bug, area: UI
