### ISSUE TITLE
bug: explore page showing testnet on livenet deployment

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#392] opened 2024-06-05 23:22 UTC
For some reason from time to time I see testnet spaces on explore page while I'm on the livenet deployment:

<img width="1468" alt="image" src="https://github.com/snapshot-labs/sx-monorepo/assets/16245250/78c9e883-b244-496a-986c-61986ec1d9aa">

**Comment by wa0x6e** [comment] 2024-06-06 17:42
Which one is the testnet spaces ?

**Comment by Sekhmet** [comment] 2024-06-07 08:21
@wa0x6e Looks like all of them (it's top spaces on testnet).
https://testnet.snapshot.org/#/

**Comment by wa0x6e** [comment] 2024-06-07 12:58
How to reproduce ? Is that on this page https://snapshotx.xyz/#/explore without any filters/search ?

**Comment by bonustrack** [comment] 2024-06-07 13:10
I'm not sure, it's inconsistent and it's not happening often but it's happening

**Comment by Sekhmet** [comment] 2024-06-10 11:27
I took a look at the code and I can't see how this could be possible. Environment variable looks good as well on this deployment. Lack of env variable shouldn't cause it either because `s-tn` is not in default list so unlikely that is issue with deployment unless we would get sx-testnet served as sx.

Might need to wait for repro 🤔

**Comment by bonustrack** [comment] 2024-06-10 11:29
I think this happened on PR deployment, which I believe come from sx-devnet

**Comment by Sekhmet** [comment] 2024-06-10 11:49
on `sx-devnet` our env is:
```
s-tn,sep,sn-sep,s,eth,matic,oeth,arb1,sn
```

so both `s` and `s-tn` are enabled.

**Comment by bonustrack** [comment] 2024-06-10 11:58
I think we should have a config var to define which env we want for the metadata like follows & profile, we can't have both

**Comment by ChaituVR** [comment] 2024-07-16 10:14
> on `sx-devnet` our env is:
> 
> ```
> s-tn,sep,sn-sep,s,eth,matic,oeth,arb1,sn
> ```
> 
> so both `s` and `s-tn` are enabled.

Why both? ideally we should have two deployments, one for `s` and `s-tn`
we haven't enabled previews for pull requests on snapshot.box. can I enable it?
<img width="744" alt="Untitled 4" src="https://github.com/user-attachments/assets/301e8d4e-5efe-4665-a848-4ee4aa7d7629">

**Comment by ChaituVR** [comment] 2024-07-16 10:19
I think we should use Vercel for previews similar to snapshot.org, have less number of issues comparatively

**Comment by wa0x6e** [comment] 2024-07-16 11:58
> > on `sx-devnet` our env is:
> > ```
> > s-tn,sep,sn-sep,s,eth,matic,oeth,arb1,sn
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > so both `s` and `s-tn` are enabled.
> 
> Why both? ideally we should have two deployments, one for `s` and one for `s-tn` we haven't enabled previews for pull requests on snapshot.box. can I enable it? <img alt="Untitled 4" width="744" src="https://private-user-images.githubusercontent.com/15967809/349041888-301e8d4e-5efe-4665-a848-4ee4aa7d7629.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEzMTEsIm5iZiI6MTcyMTEzMTAxMSwicGF0aCI6Ii8xNTk2NzgwOS8zNDkwNDE4ODgtMzAxZThkNGUtNWVmZS00NjY1LWE4NDgtNGVlNGFhN2Q3NjI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDExNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRhYjI2ZGJmOWE5MTdjNGIxOTliYmZhODNiODYyMWUzY2QzMjMwMWQxZDZkNWUyNWJiYTAyNDJjYTI2Y2Q0OWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FMxc-NI66_IjjaTysZw5QBknZWXsoWcoe3td9gv2wvo">

We already have one for `testnet` (testnet.snapshot.box), and one for `mainnet` (snapshot.box). The `devnet` (https://sx-devnet.on.fleek.co/) I think was made to reproduce same env as local env (yarn dev), where we could see all nets

**Comment by ChaituVR** [comment] 2024-07-17 06:13
In the local master, `s-tn` is not enabled though. 

On PRs, we deploy only devnet right now. 
<img width="851" alt="Untitled 2" src="https://github.com/user-attachments/assets/43135094-3aa3-4edc-bd11-cfee71238caf">

We should deploy both testnet and mainnet 🤔 if we want to do both on devnet, then we should close this issue 😄

**Comment by Sekhmet** [comment] 2024-07-17 09:35
I'd say we should make it possible to use both `s` and `s-tn` at the same time, so on PR previews (and in local dev) we can test all spaces.

The fix that we need is to make alias/follows/user profiles independent of `ENABLED_NETWORKS`, just have second flag `METADATA_NETWORK` or something like this.

**Comment by wa0x6e** [comment] 2024-07-17 09:42
That would be tricky.

Alias creation is network independent, so it will never switch to mainnet/testnet, we will have to arbitrary always use one

**Comment by Sekhmet** [comment] 2024-07-17 10:12
> Alias creation is network independent, so it will never switch to mainnet/testnet, we will have to arbitrary always use one

Is it? I can only follow mainnet spaces on `s` - `eth` works, `sep` doesn't, on the other hand with `s-tn` I can follow `sep`, but not `eth`.

**Comment by Sekhmet** [comment] 2024-08-01 15:38
Explore page will only show single offchain network at the time (controlled by `VITE_METADATA_NETWORK` env):
https://github.com/snapshot-labs/sx-monorepo/blob/e088ca6221c9ed9b04ced22476f6fed22181e20f/apps/ui/src/networks/index.ts#L82

We couldn't reproduce original issue. If it ever happens we can reopen this PR.

**Closed by Sekhmet** 2024-08-01 15:38 UTC
Labels: bug
