### ISSUE TITLE
feat: support gasless delegation sponsored by space

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#161] opened 2024-03-07 19:30 UTC
We should allow dedicated account on Mana to sponsor gasfee for delegation. Here is the flow I imagine:

- We detect on the UI that a space have enough ETH in his Mana dedicated account to activate gasless delegation
- User then instead of doing a tx to delegate he can sign a message to delegate on ERC-20 Votes contract and send it to Mana
- Mana sponsor gas fee to send a tx to `delegateBySig`

Ideally there should be a way on the UI to see which account to topup to send more credit to pay gas fee, also the space should have a way to enable or disable this feature. And there should be a way to avoid someone spam delegate actions and empty the wallet.

**More TBD**

**Comment by aurelianoB** [comment] 2024-07-31 16:11
Duplicate of https://github.com/snapshot-labs/workflow/issues/131

**Closed** 2024-07-31 16:11 UTC
Labels: area: UI, area: Mana
