### ISSUE TITLE
bug: execution treasury appear on proposal without execution

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#490] opened 2024-07-16 12:23 UTC
I tried to create a proposal without execution, but for some reason the execution treasury appear on the proposal page, we should remove it.
https://snapshot.box/#/sn:0x071977084d73002fed430d99108da39d241b900099ccc2a4cdcb7d5041d851d2/proposal/15

**Comment by ChaituVR** [comment] 2024-07-17 09:07
I am not able to reproduce, you still see it? maybe share a screenshot

**Comment by Sekhmet** [comment] 2024-07-31 21:39
Fixed in #491

**Closed by Sekhmet** 2024-07-31 21:39 UTC
Labels: bug, needs repro
