### ISSUE TITLE
bug: base network missing

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#1030] opened 2024-12-09 16:29 UTC
When I go to my space settings on the "Strategies" section, the base network doesn't appear (while it appear on https://v1.snapshot.box/#/fabien.eth/settings). 
https://snapshot.box/#/s:fabien.eth/settings/strategies

Then once I try to set "Ethereum" as base network the action failing, sequencer reply with "network not allowed"

<img width="1207" alt="image" src="https://github.com/user-attachments/assets/b415955a-d06d-4c68-b5e1-9a4028636730">

**Comment by ChaituVR** [comment] 2024-12-09 16:31
Duplicate of https://github.com/snapshot-labs/sx-monorepo/issues/1029

**Closed** 2024-12-10 03:01 UTC
Labels: bug, area: UI
