### ISSUE TITLE
bug: sticky menu 1px issue on mobile

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/sx-monorepo#330] opened 2024-05-08 23:50 UTC
On mobile with Chrome on the page votes on the sticky nav when I scroll there is a 1px transparent space between nav and filters, see under "Votes (137)" we should fix that.

https://snapshotx.xyz/#/s:safe.eth/proposal/0x5cf64434792565591b005460db0460e9314753178d4aa5475dfc0ce4d45638a2/votes

This issue was fixed in delegates page:
https://snapshotx.xyz/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c/delegates

![Screenshot_20240509_064527_Chrome](https://github.com/snapshot-labs/sx-monorepo/assets/16245250/fb027615-5a40-4065-9d97-8ac1a47c49dc)

**Comment by wa0x6e** [comment] 2024-05-09 20:40
Not able to reproduce on Chrome iOS, is it an android only issue ?

**Comment by ChaituVR** [comment] 2024-05-10 06:48
It happens randomly for me and many times we can't notice it

**Comment by wa0x6e** [comment] 2024-05-24 10:36
Fixed via #341

**Closed by wa0x6e** 2024-05-24 10:36 UTC
Labels: area: UI
